### PR TITLE
fix: scrape album-like playlists

### LINKED ISSUE #3: Cannot read properties of undefined (reading 'playlistSidebarSecondaryInfoRenderer')
Hi, I just tried to load the following playlist:
https://www.youtube.com/playlist?list=OLAK5uy_mPFpBY7OwJ9mFvKxWKzSDJUXNKY9YXjOA
And the following error occured:
```console
Error: Could not parse playlist metadata: Cannot read properties of undefined (reading 'playlistSidebarSecondaryInfoRenderer')
    at fetchFromPlaylist (...\node_modules\ytfps\out\index.js:70:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

What I noticed: The playlist does not seem to be like other playlists, maybe because it's some form of "album" playlist made by the artist themselves?

Anyways, some sort of insight would be great!

### PR DESCRIPTION
**Pull request by joshuajeschek**
fixes #3 

This just checks wether `si1` is existent, otherwise we cannot retrieve author data for the playlist. That's why I had to change the Playlist Interface (author is now optional).

I also changed properOutput, because the test was not passing on my machine.
And I also added tests for the playlist that didn't work

### CODE REVIEW

File: lib/index.ts [hunk 1]
```diff
@@ -62,15 +62,16 @@ async function fetchFromPlaylist(url: string) : Promise<YTPlaylist> {
...
                 name: si1.title.runs[0].text,
                 url: baseURL + si1.title.runs[0].navigationEndpoint.commandMetadata.webCommandMetadata.url,
                 avatar_url: si1.thumbnail.thumbnails.pop().url
-            },
+            } : undefined,
             videos: videos
         }
     } catch(e) {
-        throw Error('Could not parse playlist metadata: ' + e.message);
+        if (e instanceof Error) throw Error('Could not parse playlist metadata: ' + e.message);
```
Comment (joshuajeschek) [inline lib/index.ts:73]: I changed this catch statement because typescript was giving me troubles (maybe this changed in some typescript update since you developed it)
